### ISSUE TITLE
If tikzducks is also loaded, add the duck to random \tikzling

### ISSUE THREAD

**Issue by joulev** [samcarter/tikzlings#20]
The duck is sad for not being able to join her friends.

![image](https://user-images.githubusercontent.com/44609036/123500623-a995a980-d669-11eb-8dd4-99253c92c752.png)

**Comment by samcarter** [comment]
I would prefer to not mix the ducks and the tikzlings. The problem is that both packages provide different options. For example one can use `\tikzlings[3D]`,  which would fail with the ducks.

As a workaround you can redefine `\tikzling` to include the ducks (change 0.1 to define the probability to get a duck)

```
\documentclass{article}
\usepackage{tikzducks,tikzlings}

\makeatletter
\renewcommand{\tikzling}[1][]{%
  \pgfmathless{rnd}{0.1}
  \ifnum\pgfmathresult=1
    \randuck
  \else
    \pgfmathrandomitem{\tikzling@random}{tikzlings}%
    \tikzling@random[#1]
  \fi
}
\makeatother

\begin{document}
	\foreach \x in {0,...,100}{
\begin{tikzpicture}
	\tikzling
\end{tikzpicture}
}
	
\end{document}
```
